version: "3.8"
services:
  server:
    image: justinhorn/rust_server:1.0.1
    environment:
     - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - 80:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:latest
    ports:
      - 7878:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
networks:
  app-network:
    driver: bridge