version: "3.8"
services:
  server:
    image: rust_server
    environment:
     - POSTGRES_URL=postgres://postgres:postgres@host.docker.internal:7878/postgres
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    ports:
      - 7878:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5